include prorab.mk

this_name := r4

this_soname := 0

this_out_dir := build

# though we have no source files, we still need to indicate the C++ standard version because header files will be tested for compilation
this_cxxflags += -std=c++14

$(eval $(prorab-build-lib))
